version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -P admin -d database" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"


  minio:
    image: minio/minio:latest
    container_name: minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    command: server data

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >-
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb local/app;
      exit 0;
      "
  fastapi_app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy